# Generated by Django 3.2.18 on 2023-04-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homograph', models.CharField(max_length=255, verbose_name='Омограф')),
            ],
            options={
                'verbose_name': 'Омограф',
                'verbose_name_plural': 'Омографы',
            },
        ),
        migrations.CreateModel(
            name='QuasiSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=255, verbose_name='Наиболее близкий по значению к семантич. классу')),
                ('quasi_synonyms', models.JSONField(blank=True, null=True, verbose_name='Квазисинонимы')),
                ('homograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homograph', verbose_name='Омограф')),
            ],
            options={
                'verbose_name': 'Квазисиноним',
                'verbose_name_plural': 'Квазисинонимы',
            },
        ),
    ]
