# Generated by Django 3.2.18 on 2023-04-29 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quasisynonym',
            name='homograph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quasies', to='core.homograph', verbose_name='Омограф'),
        ),
        migrations.AlterField(
            model_name='quasisynonym',
            name='quasi_synonyms',
            field=models.JSONField(default=list, verbose_name='Квазисинонимы'),
        ),
    ]
