# Generated by Django 3.2.18 on 2023-04-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230429_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='quasisynonym',
            name='stress',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='На какой слог ударение (с нуля)'),
            preserve_default=False,
        ),
    ]
