# Generated by Django 3.2.18 on 2023-04-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quasisynonym_stress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quasisynonym',
            name='quasi_synonyms',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Квазисинонимы'),
        ),
    ]
