# Generated by Django 3.2.18 on 2023-04-29 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_quasisynonym_quasi_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quasisynonym',
            name='homograph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quasis', to='core.homograph', verbose_name='Омограф'),
        ),
    ]
