# Generated by Django 3.2.18 on 2023-05-03 09:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_quasisynonym_homograph'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackWithoutHomograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('text', models.TextField(verbose_name='Текст')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Когда был отправлен')),
            ],
            options={
                'verbose_name': 'Фидбек без омографа',
                'verbose_name_plural': 'Фидбеки без омографов',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackwithouthomograph_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.feedbackwithouthomograph')),
                ('homograph_stressed', models.CharField(max_length=255, verbose_name='Омограф с проставленным ударением')),
                ('correct', models.BooleanField(default=True, verbose_name='Правильно или нет')),
                ('where_stress_should_be', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Где должно быть ударение')),
                ('homograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.homograph', verbose_name='Омограф')),
            ],
            options={
                'verbose_name': 'Фидбек',
                'verbose_name_plural': 'Фидбеки',
            },
            bases=('core.feedbackwithouthomograph',),
        ),
    ]
