# Generated by Django 3.2.12 on 2023-05-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_quasisynonym_homograph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quasisynonym',
            name='synonym',
        ),
        migrations.AddField(
            model_name='quasisynonym',
            name='synonyms',
            field=models.JSONField(default=list, verbose_name='Наиболее близкие по значению к семантич. классу'),
        ),
    ]
