# Generated by Django 3.2.12 on 2023-05-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230504_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quasisynonym',
            name='synonyms',
            field=models.JSONField(verbose_name='Наиболее близкие по значению к семантич. классу'),
        ),
    ]
