# Generated by Django 3.2.18 on 2023-05-03 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_feedback_feedbackwithouthomograph'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='probability',
            field=models.JSONField(default=[1, 1], verbose_name='Распределение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackwithouthomograph',
            name='text_normalized',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Нормализованный текст'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='correct',
            field=models.BooleanField(default=True, verbose_name='Правильно?'),
        ),
    ]
