# Generated by Django 3.2.12 on 2023-05-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_quasisynonym_synonyms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quasisynonym',
            name='quasi_synonyms',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Квазисинонимы'),
        ),
    ]
