# Generated by Django 3.2.18 on 2023-05-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230503_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackwithouthomograph',
            name='user_id',
            field=models.PositiveBigIntegerField(verbose_name='ID пользователя'),
        ),
    ]
