# Generated by Django 3.2.12 on 2023-06-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_quasisynonym_quasi_synonyms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quasisynonym',
            name='initial_weight',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Изначальный вес'),
            preserve_default=False,
        ),
    ]
