# Generated by Django 3.2.18 on 2023-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_feedbackwithouthomograph_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quasisynonym',
            name='synonym',
        ),
        migrations.AddField(
            model_name='quasisynonym',
            name='synonyms',
            field=models.JSONField(default=list, verbose_name='Наиболее близкие по значению к семантич. классу'),
        ),
    ]
